var tipping_data = {
    round: "R1",
    admin: "Administrator",
    tips: [
	      ["R1", "Administrator", "CAR", 2, "HAW", 50, "", ""],
	      ["R1", "Daniel Terrington", "CAR", 36, "HAW", 34, "", 23],
	      ["R1", "ciniboi_12", "RIC", 3, "HAW", 19, "", 5],
	      ["R1", "Jono22", "RIC", 19, "HAW", 62, "", ""],
	      ["R1", "Steve", "CAR", 6, "HAW", 12, "", ""],
	      ["R1", "Craig Terrington", "CAR", 19, "HAW", 22, "", ""],
	      ["R2", "Administrator", "CAR", 2, "HAW", 50, 23, 0],
	      ["R2", "Administrator", "CAR", 2, "HAW", 50, 23, 0],
	      ["R2", "Administrator", "CAR", 2, "HAW", 50, 23, 0],
	      ["R2", "Administrator", "CAR", 2, "HAW", 50, 23, 0],
	      ["R2", "Administrator", "CAR", 2, "HAW", 50, 23, 0],
	      ["R2", "Administrator", "CAR", 2, "HAW", 50, 23, 0],
	      ["R2", "Administrator", "CAR", 2, "HAW", 50, 23, 0],
	      ["R2", "Administrator", "CAR", 2, "HAW", 50, 23, 0],
	      ["R2", "Administrator", "CAR", 2, "HAW", 50, 23, ""],
	      ["R2", "Administrator", "CAR", 2, "HAW", 50, 23, ""],
    ],
    fixtures: [
        ["R1", "ciniboi_12", "Daniel Terrington", "Administrator", "Jono22", "Steve", "Craig Terrington"],
        ["R2"],
        ["R3"],
	      ["R4"],
	      ["R5"],
	      ["R6"],
	      ["R7"],
        ["R8"],
        ["R9"],
	      ["R10"],
	      ["B1"],
	      ["B2"],
	      ["R14"],
        ["R15"],
        ["R16"],
	      ["R17"],
	      ["R18"],
	      ["R19"],
	      ["R20"],
        ["R21"],
        ["R22"]
    ]
}
