var tipping_data = {
    round: "R5",
    admin: "Administrator",
    tips: [
        ["R1", "Administrator", "RIC", 43, "WBD", 14, "MEL", 30, "PTA", 28, "BRI", 2, "ESS", 25, "WCE", 43, "ADE", 56, "GEE", 42, "Rory Laird (ADE)", 40, "Josh Kennedy (WCE)", 42, "", ""],
        ["R1", "Shaydog", "CAR", 15, "WBD", 25, "STK", 10, "SYD", 45, "BRI", 20, "HAW", 30, "NTH", 10, "ADE", 15, "GEE", 25, "", "", "", "", "", ""],
        ["R1", "Dannelboyz", "CAR", 6, "WBD", 18, "STK", 2, "SYD", 52, "BRI", 7, "HAW", 29, "WCE", 42, "GWS", 19, "GEE", 17, "", "", "Josh Kennedy (WCE)", 42, "", ""],
        ["R1", "Bigbadbrucey", "RIC", 23, "WBD", 37, "STK", 17, "SYD", 43, "GCS", 22, "HAW", 37, "WCE", 27, "ADE", 12, "GEE", 28, "", "", "", "", "", ""],
        ["R1", "Flagpies", "RIC", 25, "WBD", 19, "MEL", 25, "SYD", 12, "GCS", 8, "HAW", 15, "WCE", 22, "GWS", 10, "GEE", 4, "Dan Hannebery (SYD)", 18, "Travis Cloke (WBD)", 6, "", ""],
        ["R1", "Jono22", "CAR", 15, "WBD", 27, "STK", 4, "SYD", 21, "GCS", 13, "HAW", 21, "WCE", 17, "GWS", 19, "FRE", 13, "Tom Mitchell (HAW)", 37, "", "", "", ""],
        ["R1", "Kaytley🐐", "RIC", 10, "WBD", 15, "STK", 20, "SYD", 12, "BRI", 10, "HAW", 20, "WCE", 25, "ADE", 10, "FRE", 15, "", "", "", "", "", ""],
        ["R1", "Mann", "RIC", 19, "WBD", 23, "MEL", 11, "SYD", 26, "GCS", 22, "HAW", 22, "WCE", 30, "GWS", 32, "GEE", 11, "", "", "Tom Lynch (GC)", 20, "", ""],
        ["R1", "Jeanille01", "RIC", 20, "WBD", 50, "MEL", 20, "SYD", 25, "GCS", 20, "HAW", 50, "WCE", 25, "GWS", 30, "GEE", 20, "", "", "Luke Breust (HAW)", 7, "", ""],
        ["R1", "jamieling", "RIC", 17, "WBD", 33, "STK", 20, "SYD", 40, "GCS", 23, "HAW", 33, "WCE", 12, "ADE", 7, "GEE", 29, "Patrick Dangerfield (GEE)", 24, "Lance Franklin (SYD)", 26, "", ""],
        ["R1", "Alex Rowland", "RIC", 24, "WBD", 15, "STK", 20, "SYD", 31, "GCS", 11, "HAW", 26, "WCE", 33, "GWS", 28, "GEE", 23, "", "", "Josh Kennedy (WCE)", 42, "", ""],
        ["R1", "Harry Rowland", "RIC", 23, "WBD", 37, "STK", 15, "SYD", 25, "GCS", 40, "HAW", 35, "WCE", 32, "GWS", 14, "GEE", 26, "", "", "", "", "", ""],
        ["R1", "Steve", "CAR", 31, "WBD", 25, "MEL", 18, "SYD", 41, "GCS", 5, "HAW", 10, "WCE", 18, "GWS", 8, "GEE", 17, "", "", "", "", "", ""],
        ["R1", "ciniboi_12", "RIC", 40, "WBD", 32, "STK", 15, "SYD", 47, "GCS", 10, "HAW", 46, "WCE", 29, "ADE", 5, "GEE", 20, "", "", "", "", "", ""],
        ["R1", "Craig Terrington", "RIC", 15, "WBD", 35, "STK", 5, "SYD", 32, "GCS", 20, "HAW", 32, "WCE", 32, "GWS", 18, "GEE", 18, "", "", "", "", "", ""],
        ["R2", "Administrator", "RIC", 19, "WBD", 23, "ADE", 24, "GWS", 102, "ESS", 27, "WCE", 19, "GEE", 1, "MEL", 22, "PTA", 89, "Tom Mitchell (HAW)", 38, "Jeremy Cameron (GWS)", 37, "", ""],
        ["R2", "Dannelboyz", "RIC", 6, "SYD", 26, "HAW", 1, "GWS", 60, "ESS", 15, "WCE", 31, "GEE", 52, "MEL", 37, "PTA", 12, "", "", "", "", "", ""],
        ["R2", "Bigbadbrucey", "RIC", 23, "WBD", 17, "ADE", 27, "GWS", 38, "ESS", 23, "WCE", 15, "GEE", 45, "MEL", 34, "FRE", 25, "", "", "", "", "", ""],
        ["R2", "Harry Rowland", "RIC", 26, "WBD", 32, "HAW", 12, "GWS", 40, "ESS", 37, "WCE", 47, "GEE", 13, "MEL", 22, "PTA", 10, "Dan Hannebery (SYD)", 19, "", "", "", ""],
        ["R2", "Flagpies", "COL", 6, "SYD", 3, "HAW", 27, "GWS", 32, "ESS", 17, "WCE", 24, "GEE", 38, "MEL", 56, "FRE", 30, "Dustin Martin (RIC)", 25, "Lance Franklin (SYD)", 28, "", ""],
        ["R2", "Craig Terrington", "COL", 11, "WBD", 24, "ADE", 18, "GWS", 67, "BRI", 7, "WCE", 36, "GEE", 39, "MEL", 42, "PTA", 29, "", "", "", "", "", ""],
        ["R2", "Jono22", "RIC", 5, "WBD", 7, "HAW", 15, "GWS", 9, "BRI", 16, "WCE", 17, "GEE", 32, "MEL", 30, "PTA", 21, "Jaeger O'Meara (HAW)", 36, "Tom Lynch (GCS)", 2, "", ""],
        ["R2", "jamieling", "COL", 20, "WBD", 32, "ADE", 26, "GWS", 45, "ESS", 20, "WCE", 30, "GEE", 30, "MEL", 45, "PTA", 50, "", "", "", "", "", ""],
        ["R2", "Jeanille01", "COL", 10, "WBD", 20, "HAW", 20, "GWS", 30, "ESS", 20, "WCE", 30, "GEE", 30, "MEL", 40, "PTA", 40, "Patrick Dangerfield (GEE)", 37, "", "", "", ""],
        ["R2", "Kaytley🐐", "RIC", 5, "SYD", 10, "HAW", 15, "GCS", 10, "ESS", 20, "WCE", 12, "GEE", 20, "MEL", 20, "FRE", 15, "", "", "", "", "", ""],
        ["R2", "Steve", "RIC", 8, "SYD", 2, "HAW", 33, "GWS", 40, "ESS", 5, "WCE", 18, "GEE", 16, "MEL", 14, "PTA", 2, "", "", "Lance Franklin (SYD)", 28, "", ""],
        ["R2", "ciniboi_12", "COL", 11, "SYD", 25, "HAW", 3, "GWS", 37, "ESS", 19, "WCE", 45, "GEE", 6, "MEL", 55, "PTA", 35, "Nathan Jones (MEL)", 24, "", "", "", ""],
        ["R2", "Alex Rowland", "COL", 12, "WBD", 10, "HAW", 18, "GWS", 33, "ESS", 28, "WCE", 38, "GEE", 44, "MEL", 25, "PTA", 31, "Patrick Dangerfield (GEE)", 37, "", "", "", ""],
        ["R2", "Mann", "COL", 1, "WBD", 5, "HAW", 1, "GWS", 32, "ESS", 13, "WCE", 38, "GEE", 32, "MEL", 36, "PTA", 25, "Tom Mitchell (HAW)", 38, "Josh Kennedy (WCE)", 25, "", ""],
        ["R2", "Shaydog", "COL", 15, "WBD", 10, "HAW", 25, "GWS", 15, "ESS", 25, "STK", 5, "GEE", 20, "MEL", 30, "FRE", 20, "Patrick Dangerfield (GEE)", 37, "", "", "", ""],
        ["R3", "Administrator", "COL", 1, "GWS", 42, "RIC", 11, "GEE", 29, "ADE", 17, "FRE", 16, "STK", 31, "CAR", 15, "GCS", 86, "Dustin Martin (RIC)", 40, "Brandon Matera (GCS)", 36, "", ""],
        ["R3", "Jono22", "SYD", 27, "GWS", 25, "WCE", 13, "MEL", 15, "ADE", 14, "FRE", 15, "STK", 31, "ESS", 16, "HAW", 27, "", "", "", "", "", ""],
        ["R3", "Jeanille01", "SYD", 20, "GWS", 20, "WCE", 30, "MEL", 10, "ADE", 20, "WBD", 30, "STK", 40, "ESS", 30, "HAW", 30, "Gary Ablett (GCS)", 36, "", "", "", ""],
        ["R3", "Dannelboyz", "SYD", 19, "GWS", 60, "WCE", 24, "GEE", 6, "ADE", 33, "WBD", 56, "STK", 19, "ESS", 7, "HAW", 32, "Adam Treloar (COL)", 28, "", "", "", ""],
        ["R3", "Bigbadbrucey", "SYD", 23, "GWS", 37, "RIC", 1, "GEE", 25, "ADE", 29, "WBD", 40, "STK", 40, "ESS", 30, "HAW", 35, "Jaeger O'Meara (HAW)", 14, "Tim Membrey (STK)", 9, "", ""],
        ["R3", "Kaytley🐐", "SYD", 15, "GWS", 10, "RIC", 10, "GEE", 20, "ADE", 5, "WBD", 15, "BRI", 10, "ESS", 25, "HAW", 10, "", "", "", "", "", ""],
        ["R3", "Steve", "SYD", 42, "GWS", 33, "WCE", 5, "GEE", 18, "ADE", 41, "WBD", 60, "STK", 15, "ESS", 27, "HAW", 48, "Scott Pendlebury (COL)", 26, "", "", "", ""],
        ["R3", "Mann", "SYD", 18, "GWS", 37, "WCE", 16, "GEE", 14, "PTA", 1, "WBD", 38, "STK", 38, "ESS", 28, "HAW", 42, "Jaeger O'Meara (HAW)", 14, "Lance Franklin (SYD)", 3, "", ""],
        ["R3", "Harry Rowland", "COL", 6, "GWS", 20, "WCE", 45, "GEE", 20, "ADE", 16, "WBD", 25, "BRI", 15, "ESS", 32, "HAW", 21, "", "", "Lance Franklin (SYD)", 3, "", ""],
        ["R3", "Flagpies", "SYD", 15, "NTH", 3, "RIC", 16, "GEE", 10, "ADE", 20, "WBD", 15, "BRI", 13, "ESS", 20, "HAW", 21, "", "", "", "", "", ""],
        ["R3", "Shaydog", "SYD", 15, "GWS", 12, "RIC", 10, "MEL", 18, "PTA", 8, "WBD", 20, "BRI", 17, "ESS", 25, "HAW", 16, "", "", "Josh Kennedy (WCE)", 13, "", ""],
        ["R3", "jamieling", "SYD", 33, "GWS", 40, "WCE", 15, "GEE", 30, "ADE", 5, "WBD", 60, "STK", 35, "ESS", 25, "HAW", 37, "", "", "", "", "", ""],
        ["R3", "Alex Rowland", "SYD", 25, "GWS", 36, "RIC", 5, "GEE", 21, "ADE", 16, "WBD", 32, "STK", 22, "ESS", 18, "HAW", 26, "", "", "Jeremy Cameron (GWS)", 21, "", ""],
        ["R3", "ciniboi_12", "SYD", 15, "GWS", 31, "WCE", 22, "GEE", 5, "ADE", 28, "WBD", 10, "STK", 58, "ESS", 8, "HAW", 42, "Zach Merrett (ESS)", 29, "Lance Franklin (SYD)", 3, "", ""],
        ["R3", "Craig Terrington", "SYD", 32, "GWS", 42, "WCE", 21, "GEE", 33, "ADE", 9, "WBD", 41, "STK", 29, "ESS", 12, "HAW", 47, "", "", "", "", "", ""],
        ["R4", "Administrator", "WCE", 26, "WBD", 3, "FRE", 2, "GWS", 31, "GCS", 26, "ADE", 65, "STK", 14, "RIC", 52, "GEE", 86, "Taylor Adams (COL)", 39, "Tom Lynch (GCS)", 42, "", ""],
        ["R4", "Jono22", "WCE", 9, "WBD", 14, "MEL", 7, "GWS", 14, "GCS", 16, "ADE", 27, "STK", 24, "RIC", 14, "HAW", 3, "Gary Ablett (GCS)", 34, "Josh Jenkins (ADE)", "", "", ""],
        ["R4", "Jeanille01", "WCE", 30, "WBD", 30, "MEL", 30, "GWS", 40, "CAR", 10, "ADE", 30, "STK", 25, "RIC", 15, "HAW", 10, "", "", "Josh Kennedy (WCE)", 15, "", ""],
        ["R4", "Dannelboyz", "WCE", 4, "WBD", 45, "MEL", 18, "GWS", 31, "GCS", 2, "ADE", 40, "COL", 7, "RIC", 26, "HAW", 1, "Patrick Dangerfield (GEE)", 27, "", "", "", ""],
        ["R4", "Kaytley🐐", "WCE", 17, "WBD", 21, "MEL", 7, "GWS", 15, "CAR", 10, "ADE", 25, "COL", 15, "RIC", 22, "HAW", 5, "", "", "", "", "", ""],
        ["R4", "Bigbadbrucey", "WCE", 5, "WBD", 33, "MEL", 35, "GWS", 35, "GCS", 10, "ADE", 40, "STK", 15, "RIC", 25, "GEE", 17, "", "", "", "", "", ""],
        ["R4", "Mann", "WCE", 23, "WBD", 22, "MEL", 19, "GWS", 28, "CAR", 3, "ADE", 32, "STK", 7, "RIC", 23, "HAW", 1, "Tom Mitchell (HAW)", 32, "", "", "", ""],
        ["R4", "Steve", "WCE", 18, "WBD", 36, "MEL", 16, "GWS", 33, "CAR", 2, "ADE", 19, "STK", 16, "RIC", 40, "GEE", 60, "", "", "Tom Hawkins (GEE)", 26, "", ""],
        ["R4", "Shaydog", "WCE", 13, "WBD", 11, "MEL", 24, "PTA", 22, "CAR", 5, "ESS", 8, "COL", 16, "RIC", 18, "GEE", 22, "Patrick Dangerfield (GEE)", 27, "Jeremy Cameron (GWS)", 9, "", ""],
        ["R4", "Flagpies", "WCE", 12, "WBD", 36, "MEL", 20, "GWS", 14, "CAR", 28, "ESS", 16, "COL", 15, "RIC", 20, "GEE", 20, "", "", "", "", "", ""],
        ["R4", "Harry Rowland", "WCE", 15, "WBD", 22, "MEL", 14, "PTA", 31, "GCS", 24, "ESS", 23, "COL", 5, "BRI", 8, "HAW", 2, "", "", "", "", "", ""],
        ["R4", "jamieling", "WCE", 20, "WBD", 35, "MEL", 18, "GWS", 22, "GCS", 19, "ADE", 33, "STK", 22, "RIC", 25, "GEE", 40, "Patrick Dangerfield (GEE)", 27, "Jack Riewoldt (RIC)", 26, "", ""],
        ["R4", "Craig Terrington", "WCE", 11, "WBD", 21, "MEL", 9, "GWS", 29, "GCS", 6, "ADE", 57, "COL", 12, "RIC", 39, "GEE", 17, "", "", "", "", "", ""],
        ["R4", "Alex Rowland", "WCE", 10, "WBD", 23, "MEL", 36, "GWS", 5, "CAR", 13, "ADE", 28, "STK", 16, "RIC", 33, "GEE", 7, "Tom Mitchell (HAW)", 32, "", "", "", ""],
        ["R4", "ciniboi_12", "SYD", 11, "WBD", 24, "MEL", 36, "GWS", 17, "GCS", 6, "ADE", 42, "STK", 15, "BRI", 1, "HAW", 5, "", "", "", "", "", ""],
        ["R5", "Dannelboyz", "PTA", 24, "WBD", 40, "ADE", 35, "GWS", 19, "NTH", 2, "GEE", 7, "WCE", 29, "MEL", 6, "COL", 15, "", "", "", "", "", ""],
        ["R5", "Bigbadbrucey", "PTA", 27, "WBD", 28, "ADE", 22, "GWS", 10, "FRE", 10, "STK", 5, "WCE", 5, "RIC", 10, "ESS", 5, "", "", "", "", "", ""],
        ["R5", "Harry Rowland", "PTA", 30, "WBD", 40, "ADE", 20, "GWS", 15, "FRE", 32, "GEE", 23, "HAW", 1, "RIC", 20, "ESS", 25, "", "", "Patrick Dangerfield (GEE)", "", "", ""],
        ["R5", "Mann", "PTA", 39, "WBD", 44, "ADE", 36, "GWS", 15, "FRE", 17, "GEE", 15, "HAW", 1, "MEL", 2, "ESS", 16, "", "", "", "", "", ""],
        ["R5", "Kaytley🐐", "CAR", 15, "WBD", 25, "GCS", 15, "SYD", 15, "FRE", 20, "GEE", 15, "HAW", 20, "RIC", 15, "ESS", 5, "Rory Sloane (ADE)", "", "Josh Kennedy (WCE)", "", "", ""],
        ["R5", "Shaydog", "PTA", 15, "WBD", 20, "ADE", 22, "GWS", 28, "FRE", 13, "GEE", 28, "WCE", 27, "RIC", 11, "ESS", 10, "", "", "", "", "", ""],
        ["R5", "Steve", "PTA", 32, "WBD", 42, "ADE", 33, "SYD", 5, "FRE", 18, "GEE", 36, "WCE", 15, "RIC", 21, "ESS", 14, "Scott Pendlebury (COL)", "", "", "", "", ""]
    ],
    fixtures: [
        ["R1", "Shaydog", "Dannelboyz", "Bigbadbrucey", "Flagpies", "Jono22", "ciniboi_12", "Craig Terrington", "Alex Rowland", "Mann", "Steve", "Harry Rowland", "Kaytley🐐", "jamieling", "Jeanille01"],
        ["R2", "Dannelboyz", "Jeanille01", "Kaytley🐐", "jamieling", "Steve", "Harry Rowland", "Alex Rowland", "Mann", "ciniboi_12", "Craig Terrington", "Flagpies", "Jono22", "Shaydog", "Bigbadbrucey"],
        ["R3", "Bigbadbrucey", "Dannelboyz", "Jono22", "Shaydog", "Craig Terrington", "Flagpies", "Mann", "ciniboi_12", "Harry Rowland", "Alex Rowland", "jamieling", "Steve", "Jeanille01", "Kaytley🐐"],
        ["R4", "Dannelboyz", "Kaytley🐐", "Steve", "Jeanille01", "Alex Rowland", "jamieling", "ciniboi_12", "Harry Rowland", "Flagpies", "Mann", "Shaydog", "Craig Terrington", "Bigbadbrucey", "Jono22"],
        ["R5", "Jono22", "Dannelboyz", "Craig Terrington", "Bigbadbrucey", "Mann", "Shaydog", "Harry Rowland", "Flagpies", "jamieling", "ciniboi_12", "Jeanille01", "Alex Rowland", "Kaytley🐐", "Steve"],
        ["R6", "Dannelboyz", "Steve", "Alex Rowland", "Kaytley🐐", "ciniboi_12", "Jeanille01", "Flagpies", "jamieling", "Shaydog", "Harry Rowland", "Bigbadbrucey", "Mann", "Jono22", "Craig Terrington"],
        ["R7", "Craig Terrington", "Dannelboyz", "Mann", "Jono22", "Harry Rowland", "Bigbadbrucey", "jamieling", "Shaydog", "Jeanille01", "Flagpies", "Kaytley🐐", "ciniboi_12", "Steve", "Alex Rowland"],
        ["R8", "Dannelboyz", "Alex Rowland", "ciniboi_12", "Steve", "Flagpies", "Kaytley🐐", "Shaydog", "Jeanille01", "Bigbadbrucey", "jamieling", "Jono22", "Harry Rowland", "Craig Terrington", "Mann"],
        ["R9", "Mann", "Dannelboyz", "Harry Rowland", "Craig Terrington", "jamieling", "Jono22", "Jeanille01", "Bigbadbrucey", "Kaytley🐐", "Shaydog", "Steve", "Flagpies", "Alex Rowland", "ciniboi_12"],
        ["R10", "Dannelboyz", "ciniboi_12", "Flagpies", "Alex Rowland", "Shaydog", "Steve", "Bigbadbrucey", "Kaytley🐐", "Jono22", "Jeanille01", "Craig Terrington", "jamieling", "Mann", "Harry Rowland"],
        ["B1", "Harry Rowland", "Dannelboyz", "jamieling", "Mann", "Jeanille01", "Craig Terrington", "Kaytley🐐", "Jono22", "Steve", "Bigbadbrucey", "Alex Rowland", "Shaydog", "ciniboi_12", "Flagpies"],
        ["B2", "Dannelboyz", "Flagpies", "Shaydog", "ciniboi_12", "Bigbadbrucey", "Alex Rowland", "Jono22", "Steve", "Craig Terrington", "Kaytley🐐", "Mann", "Jeanille01", "Harry Rowland", "jamieling"],
        ["R14", "jamieling", "Dannelboyz", "Jeanille01", "Harry Rowland", "Kaytley🐐", "Mann", "Steve", "Craig Terrington", "Alex Rowland", "Jono22", "ciniboi_12", "Bigbadbrucey", "Flagpies", "Shaydog"],
        ["R15", "Shaydog", "Dannelboyz", "Bigbadbrucey", "Flagpies", "Jono22", "ciniboi_12", "Craig Terrington", "Alex Rowland", "Mann", "Steve", "Harry Rowland", "Kaytley🐐", "jamieling", "Jeanille01"],
        ["R16", "Dannelboyz", "Jeanille01", "Kaytley🐐", "jamieling", "Steve", "Harry Rowland", "Alex Rowland", "Mann", "ciniboi_12", "Craig Terrington", "Flagpies", "Jono22", "Shaydog", "Bigbadbrucey"],
        ["R17", "Bigbadbrucey", "Dannelboyz", "Jono22", "Shaydog", "Craig Terrington", "Flagpies", "Mann", "ciniboi_12", "Harry Rowland", "Alex Rowland", "jamieling", "Steve", "Jeanille01", "Kaytley🐐"],
        ["R18", "Dannelboyz", "Kaytley🐐", "Steve", "Jeanille01", "Alex Rowland", "jamieling", "ciniboi_12", "Harry Rowland", "Flagpies", "Mann", "Shaydog", "Craig Terrington", "Bigbadbrucey", "Jono22"],
        ["R19", "Jono22", "Dannelboyz", "Craig Terrington", "Bigbadbrucey", "Mann", "Shaydog", "Harry Rowland", "Flagpies", "jamieling", "ciniboi_12", "Jeanille01", "Alex Rowland", "Kaytley🐐", "Steve"],
        ["R20", "Dannelboyz", "Steve", "Alex Rowland", "Kaytley🐐", "ciniboi_12", "Jeanille01", "Flagpies", "jamieling", "Shaydog", "Harry Rowland", "Bigbadbrucey", "Mann", "Jono22", "Craig Terrington"],
        ["R21", "Craig Terrington", "Dannelboyz", "Mann", "Jono22", "Harry Rowland", "Bigbadbrucey", "jamieling", "Shaydog", "Jeanille01", "Flagpies", "Kaytley🐐", "ciniboi_12", "Steve", "Alex Rowland"],
        ["R22", "Dannelboyz", "Alex Rowland", "ciniboi_12", "Steve", "Flagpies", "Kaytley🐐", "Shaydog", "Jeanille01", "Bigbadbrucey", "jamieling", "Jono22", "Harry Rowland", "Craig Terrington", "Mann"],
        ["R23", "Mann", "Dannelboyz", "Harry Rowland", "Craig Terrington", "jamieling", "Jono22", "Jeanille01", "Bigbadbrucey", "Kaytley🐐", "Shaydog", "Steve", "Flagpies", "Alex Rowland", "ciniboi_12"]
    ]
}
